# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgvActionEvent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgvActionEvent.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\023AgvActionEventProto'),
  serialized_pb=_b('\n\x14\x41gvActionEvent.proto\x1a\x11MessageBase.proto\"\xfd\x05\n\x15\x41gvActionEventMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12=\n\x0e\x61gvActionEvent\x18\x02 \x01(\x0b\x32%.AgvActionEventMessage.AgvActionEvent\x1a\x81\x05\n\x0e\x41gvActionEvent\x12\r\n\x05\x61gvId\x18\x01 \x01(\t\x12\x0f\n\x07traceId\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63tionId\x18\x03 \x01(\t\x12H\n\nactionType\x18\x04 \x01(\x0e\x32\x34.AgvActionEventMessage.AgvActionEvent.ActionTypeEnum\x12J\n\x0b\x61\x63tionEvent\x18\x05 \x01(\x0e\x32\x35.AgvActionEventMessage.AgvActionEvent.ActionEventEnum\x12\x12\n\nactionMeta\x18\x06 \x01(\t\"\xaf\x02\n\x0e\x41\x63tionTypeEnum\x12\x0f\n\x0b\x41\x43TION_MOVE\x10\x00\x12\x0f\n\x0b\x41\x43TION_LIFT\x10\x01\x12\x0e\n\nACTION_PUT\x10\x02\x12\x0f\n\x0b\x41\x43TION_READ\x10\x03\x12\x0f\n\x0b\x41\x43TION_TURN\x10\x04\x12\x11\n\rACTION_ROTATE\x10\x05\x12\x11\n\rACTION_CHARGE\x10\x06\x12\x13\n\x0f\x41\x43TION_UNCHARGE\x10\x07\x12\x16\n\x12\x41\x43TION_CLEAR_ERROR\x10\x08\x12\x10\n\x0c\x41\x43TION_CLEAR\x10\t\x12\x14\n\x10\x41\x43TION_CLEAR_ALL\x10\n\x12\x14\n\x10\x41\x43TION_WORK_MODE\x10\x0b\x12\x10\n\x0c\x41\x43TION_PAUSE\x10\x0c\x12\x11\n\rACTION_RESUME\x10\r\x12\x13\n\x0f\x41\x43TION_BACKWARD\x10\x0e\"a\n\x0f\x41\x63tionEventEnum\x12\x13\n\x0f\x41\x43TION_RECEIVED\x10\x00\x12\x11\n\rACTION_REJECT\x10\x01\x12\x14\n\x10\x41\x43TION_COMPLETED\x10\x02\x12\x10\n\x0c\x41\x43TION_ERROR\x10\x03\x42\x42\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x13\x41gvActionEventProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])



_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONTYPEENUM = _descriptor.EnumDescriptor(
  name='ActionTypeEnum',
  full_name='AgvActionEventMessage.AgvActionEvent.ActionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_MOVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_LIFT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_PUT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_READ', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_TURN', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_ROTATE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CHARGE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_UNCHARGE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CLEAR_ERROR', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CLEAR', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CLEAR_ALL', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_WORK_MODE', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_PAUSE', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_RESUME', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_BACKWARD', index=14, number=14,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=407,
  serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONTYPEENUM)

_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONEVENTENUM = _descriptor.EnumDescriptor(
  name='ActionEventEnum',
  full_name='AgvActionEventMessage.AgvActionEvent.ActionEventEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_RECEIVED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_REJECT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_COMPLETED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=712,
  serialized_end=809,
)
_sym_db.RegisterEnumDescriptor(_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONEVENTENUM)


_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT = _descriptor.Descriptor(
  name='AgvActionEvent',
  full_name='AgvActionEventMessage.AgvActionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agvId', full_name='AgvActionEventMessage.AgvActionEvent.agvId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traceId', full_name='AgvActionEventMessage.AgvActionEvent.traceId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionId', full_name='AgvActionEventMessage.AgvActionEvent.actionId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionType', full_name='AgvActionEventMessage.AgvActionEvent.actionType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionEvent', full_name='AgvActionEventMessage.AgvActionEvent.actionEvent', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionMeta', full_name='AgvActionEventMessage.AgvActionEvent.actionMeta', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONTYPEENUM,
    _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONEVENTENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=809,
)

_AGVACTIONEVENTMESSAGE = _descriptor.Descriptor(
  name='AgvActionEventMessage',
  full_name='AgvActionEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='AgvActionEventMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agvActionEvent', full_name='AgvActionEventMessage.agvActionEvent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=809,
)

_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT.fields_by_name['actionType'].enum_type = _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONTYPEENUM
_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT.fields_by_name['actionEvent'].enum_type = _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONEVENTENUM
_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT.containing_type = _AGVACTIONEVENTMESSAGE
_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONTYPEENUM.containing_type = _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT
_AGVACTIONEVENTMESSAGE_AGVACTIONEVENT_ACTIONEVENTENUM.containing_type = _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT
_AGVACTIONEVENTMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_AGVACTIONEVENTMESSAGE.fields_by_name['agvActionEvent'].message_type = _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT
DESCRIPTOR.message_types_by_name['AgvActionEventMessage'] = _AGVACTIONEVENTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgvActionEventMessage = _reflection.GeneratedProtocolMessageType('AgvActionEventMessage', (_message.Message,), dict(

  AgvActionEvent = _reflection.GeneratedProtocolMessageType('AgvActionEvent', (_message.Message,), dict(
    DESCRIPTOR = _AGVACTIONEVENTMESSAGE_AGVACTIONEVENT,
    __module__ = 'AgvActionEvent_pb2'
    # @@protoc_insertion_point(class_scope:AgvActionEventMessage.AgvActionEvent)
    ))
  ,
  DESCRIPTOR = _AGVACTIONEVENTMESSAGE,
  __module__ = 'AgvActionEvent_pb2'
  # @@protoc_insertion_point(class_scope:AgvActionEventMessage)
  ))
_sym_db.RegisterMessage(AgvActionEventMessage)
_sym_db.RegisterMessage(AgvActionEventMessage.AgvActionEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
