# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgvAction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgvAction.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\016AgvActionProto'),
  serialized_pb=_b('\n\x0f\x41gvAction.proto\x1a\x11MessageBase.proto\"\xd8\x07\n\x10\x41gvActionMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12.\n\tagvAction\x18\x02 \x01(\x0b\x32\x1b.AgvActionMessage.AgvAction\x1a\xf0\x06\n\tAgvAction\x12\r\n\x05\x61gvId\x18\x01 \x01(\t\x12\x0f\n\x07traceId\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63tionId\x18\x03 \x01(\t\x12>\n\nactionType\x18\x04 \x01(\x0e\x32*.AgvActionMessage.AgvAction.ActionTypeEnum\x12=\n\x0c\x63urrentPoint\x18\x05 \x01(\x0b\x32\'.AgvActionMessage.AgvAction.ActionPoint\x12\x37\n\x06points\x18\x06 \x03(\x0b\x32\'.AgvActionMessage.AgvAction.ActionPoint\x12\x12\n\nbucketCode\x18\x07 \x01(\t\x12\x12\n\nbucketFace\x18\x08 \x01(\t\x12\x13\n\x0b\x64irectionId\x18\t \x01(\x05\x12\x12\n\nfollowFlag\x18\n \x01(\x08\x12;\n\x08workMode\x18\x0b \x01(\x0e\x32).AgvActionMessage.AgvAction.AgvStatusEnum\x12\x12\n\nretryTimes\x18\x0c \x01(\x05\x1a`\n\x0b\x41\x63tionPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07originX\x18\x02 \x01(\x01\x12\x0f\n\x07originY\x18\x03 \x01(\x01\x12\x10\n\x08\x64istance\x18\x04 \x01(\x01\x12\x11\n\tdirection\x18\x05 \x01(\x01\"\xaf\x02\n\x0e\x41\x63tionTypeEnum\x12\x0f\n\x0b\x41\x43TION_MOVE\x10\x00\x12\x0f\n\x0b\x41\x43TION_LIFT\x10\x01\x12\x0e\n\nACTION_PUT\x10\x02\x12\x0f\n\x0b\x41\x43TION_READ\x10\x03\x12\x0f\n\x0b\x41\x43TION_TURN\x10\x04\x12\x11\n\rACTION_ROTATE\x10\x05\x12\x11\n\rACTION_CHARGE\x10\x06\x12\x13\n\x0f\x41\x43TION_UNCHARGE\x10\x07\x12\x16\n\x12\x41\x43TION_CLEAR_ERROR\x10\x08\x12\x10\n\x0c\x41\x43TION_CLEAR\x10\t\x12\x14\n\x10\x41\x43TION_CLEAR_ALL\x10\n\x12\x14\n\x10\x41\x43TION_WORK_MODE\x10\x0b\x12\x10\n\x0c\x41\x43TION_PAUSE\x10\x0c\x12\x11\n\rACTION_RESUME\x10\r\x12\x13\n\x0f\x41\x43TION_BACKWARD\x10\x0e\"C\n\rAgvStatusEnum\x12\x0b\n\x07OFFLINE\x10\x00\x12\t\n\x05\x42\x41SIC\x10\x01\x12\n\n\x06ONLINE\x10\x02\x12\x0e\n\nREGISTERED\x10\x03\x42=\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x0e\x41gvActionProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])



_AGVACTIONMESSAGE_AGVACTION_ACTIONTYPEENUM = _descriptor.EnumDescriptor(
  name='ActionTypeEnum',
  full_name='AgvActionMessage.AgvAction.ActionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_MOVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_LIFT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_PUT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_READ', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_TURN', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_ROTATE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CHARGE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_UNCHARGE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CLEAR_ERROR', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CLEAR', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CLEAR_ALL', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_WORK_MODE', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_PAUSE', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_RESUME', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_BACKWARD', index=14, number=14,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=651,
  serialized_end=954,
)
_sym_db.RegisterEnumDescriptor(_AGVACTIONMESSAGE_AGVACTION_ACTIONTYPEENUM)

_AGVACTIONMESSAGE_AGVACTION_AGVSTATUSENUM = _descriptor.EnumDescriptor(
  name='AgvStatusEnum',
  full_name='AgvActionMessage.AgvAction.AgvStatusEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASIC', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTERED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=956,
  serialized_end=1023,
)
_sym_db.RegisterEnumDescriptor(_AGVACTIONMESSAGE_AGVACTION_AGVSTATUSENUM)


_AGVACTIONMESSAGE_AGVACTION_ACTIONPOINT = _descriptor.Descriptor(
  name='ActionPoint',
  full_name='AgvActionMessage.AgvAction.ActionPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AgvActionMessage.AgvAction.ActionPoint.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='originX', full_name='AgvActionMessage.AgvAction.ActionPoint.originX', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='originY', full_name='AgvActionMessage.AgvAction.ActionPoint.originY', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='AgvActionMessage.AgvAction.ActionPoint.distance', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='AgvActionMessage.AgvAction.ActionPoint.direction', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=648,
)

_AGVACTIONMESSAGE_AGVACTION = _descriptor.Descriptor(
  name='AgvAction',
  full_name='AgvActionMessage.AgvAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agvId', full_name='AgvActionMessage.AgvAction.agvId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traceId', full_name='AgvActionMessage.AgvAction.traceId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionId', full_name='AgvActionMessage.AgvAction.actionId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionType', full_name='AgvActionMessage.AgvAction.actionType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPoint', full_name='AgvActionMessage.AgvAction.currentPoint', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='AgvActionMessage.AgvAction.points', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucketCode', full_name='AgvActionMessage.AgvAction.bucketCode', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucketFace', full_name='AgvActionMessage.AgvAction.bucketFace', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='directionId', full_name='AgvActionMessage.AgvAction.directionId', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followFlag', full_name='AgvActionMessage.AgvAction.followFlag', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workMode', full_name='AgvActionMessage.AgvAction.workMode', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retryTimes', full_name='AgvActionMessage.AgvAction.retryTimes', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGVACTIONMESSAGE_AGVACTION_ACTIONPOINT, ],
  enum_types=[
    _AGVACTIONMESSAGE_AGVACTION_ACTIONTYPEENUM,
    _AGVACTIONMESSAGE_AGVACTION_AGVSTATUSENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=1023,
)

_AGVACTIONMESSAGE = _descriptor.Descriptor(
  name='AgvActionMessage',
  full_name='AgvActionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='AgvActionMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agvAction', full_name='AgvActionMessage.agvAction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGVACTIONMESSAGE_AGVACTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=1023,
)

_AGVACTIONMESSAGE_AGVACTION_ACTIONPOINT.containing_type = _AGVACTIONMESSAGE_AGVACTION
_AGVACTIONMESSAGE_AGVACTION.fields_by_name['actionType'].enum_type = _AGVACTIONMESSAGE_AGVACTION_ACTIONTYPEENUM
_AGVACTIONMESSAGE_AGVACTION.fields_by_name['currentPoint'].message_type = _AGVACTIONMESSAGE_AGVACTION_ACTIONPOINT
_AGVACTIONMESSAGE_AGVACTION.fields_by_name['points'].message_type = _AGVACTIONMESSAGE_AGVACTION_ACTIONPOINT
_AGVACTIONMESSAGE_AGVACTION.fields_by_name['workMode'].enum_type = _AGVACTIONMESSAGE_AGVACTION_AGVSTATUSENUM
_AGVACTIONMESSAGE_AGVACTION.containing_type = _AGVACTIONMESSAGE
_AGVACTIONMESSAGE_AGVACTION_ACTIONTYPEENUM.containing_type = _AGVACTIONMESSAGE_AGVACTION
_AGVACTIONMESSAGE_AGVACTION_AGVSTATUSENUM.containing_type = _AGVACTIONMESSAGE_AGVACTION
_AGVACTIONMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_AGVACTIONMESSAGE.fields_by_name['agvAction'].message_type = _AGVACTIONMESSAGE_AGVACTION
DESCRIPTOR.message_types_by_name['AgvActionMessage'] = _AGVACTIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgvActionMessage = _reflection.GeneratedProtocolMessageType('AgvActionMessage', (_message.Message,), dict(

  AgvAction = _reflection.GeneratedProtocolMessageType('AgvAction', (_message.Message,), dict(

    ActionPoint = _reflection.GeneratedProtocolMessageType('ActionPoint', (_message.Message,), dict(
      DESCRIPTOR = _AGVACTIONMESSAGE_AGVACTION_ACTIONPOINT,
      __module__ = 'AgvAction_pb2'
      # @@protoc_insertion_point(class_scope:AgvActionMessage.AgvAction.ActionPoint)
      ))
    ,
    DESCRIPTOR = _AGVACTIONMESSAGE_AGVACTION,
    __module__ = 'AgvAction_pb2'
    # @@protoc_insertion_point(class_scope:AgvActionMessage.AgvAction)
    ))
  ,
  DESCRIPTOR = _AGVACTIONMESSAGE,
  __module__ = 'AgvAction_pb2'
  # @@protoc_insertion_point(class_scope:AgvActionMessage)
  ))
_sym_db.RegisterMessage(AgvActionMessage)
_sym_db.RegisterMessage(AgvActionMessage.AgvAction)
_sym_db.RegisterMessage(AgvActionMessage.AgvAction.ActionPoint)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
