# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgvGetOriginPointRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgvGetOriginPointRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\035AgvGetOriginPointRequestProto'),
  serialized_pb=_b('\n\x1e\x41gvGetOriginPointRequest.proto\x1a\x11MessageBase.proto\"\xef\x01\n\x1f\x41gvGetOriginPointRequestMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12[\n\x18\x61gvGetOriginPointRequest\x18\x02 \x01(\x0b\x32\x39.AgvGetOriginPointRequestMessage.AgvGetOriginPointRequest\x1aL\n\x18\x41gvGetOriginPointRequest\x12\x10\n\x08logicalX\x18\x01 \x01(\x05\x12\x10\n\x08logicalY\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x42L\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x1d\x41gvGetOriginPointRequestProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])




_AGVGETORIGINPOINTREQUESTMESSAGE_AGVGETORIGINPOINTREQUEST = _descriptor.Descriptor(
  name='AgvGetOriginPointRequest',
  full_name='AgvGetOriginPointRequestMessage.AgvGetOriginPointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logicalX', full_name='AgvGetOriginPointRequestMessage.AgvGetOriginPointRequest.logicalX', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logicalY', full_name='AgvGetOriginPointRequestMessage.AgvGetOriginPointRequest.logicalY', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='AgvGetOriginPointRequestMessage.AgvGetOriginPointRequest.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=293,
)

_AGVGETORIGINPOINTREQUESTMESSAGE = _descriptor.Descriptor(
  name='AgvGetOriginPointRequestMessage',
  full_name='AgvGetOriginPointRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='AgvGetOriginPointRequestMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agvGetOriginPointRequest', full_name='AgvGetOriginPointRequestMessage.agvGetOriginPointRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGVGETORIGINPOINTREQUESTMESSAGE_AGVGETORIGINPOINTREQUEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=293,
)

_AGVGETORIGINPOINTREQUESTMESSAGE_AGVGETORIGINPOINTREQUEST.containing_type = _AGVGETORIGINPOINTREQUESTMESSAGE
_AGVGETORIGINPOINTREQUESTMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_AGVGETORIGINPOINTREQUESTMESSAGE.fields_by_name['agvGetOriginPointRequest'].message_type = _AGVGETORIGINPOINTREQUESTMESSAGE_AGVGETORIGINPOINTREQUEST
DESCRIPTOR.message_types_by_name['AgvGetOriginPointRequestMessage'] = _AGVGETORIGINPOINTREQUESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgvGetOriginPointRequestMessage = _reflection.GeneratedProtocolMessageType('AgvGetOriginPointRequestMessage', (_message.Message,), dict(

  AgvGetOriginPointRequest = _reflection.GeneratedProtocolMessageType('AgvGetOriginPointRequest', (_message.Message,), dict(
    DESCRIPTOR = _AGVGETORIGINPOINTREQUESTMESSAGE_AGVGETORIGINPOINTREQUEST,
    __module__ = 'AgvGetOriginPointRequest_pb2'
    # @@protoc_insertion_point(class_scope:AgvGetOriginPointRequestMessage.AgvGetOriginPointRequest)
    ))
  ,
  DESCRIPTOR = _AGVGETORIGINPOINTREQUESTMESSAGE,
  __module__ = 'AgvGetOriginPointRequest_pb2'
  # @@protoc_insertion_point(class_scope:AgvGetOriginPointRequestMessage)
  ))
_sym_db.RegisterMessage(AgvGetOriginPointRequestMessage)
_sym_db.RegisterMessage(AgvGetOriginPointRequestMessage.AgvGetOriginPointRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
