# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgvRegisterRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgvRegisterRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\027AgvRegisterRequestProto'),
  serialized_pb=_b('\n\x18\x41gvRegisterRequest.proto\x1a\x11MessageBase.proto\"\xf0\x04\n\x19\x41gvRegisterRequestMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12I\n\x12\x61gvRegisterRequest\x18\x02 \x01(\x0b\x32-.AgvRegisterRequestMessage.AgvRegisterRequest\x1a\xe4\x03\n\x12\x41gvRegisterRequest\x12\x0f\n\x07\x61gvCode\x18\x01 \x01(\t\x12\x11\n\tinitPower\x18\x02 \x01(\x02\x12\x0c\n\x04\x63urX\x18\x03 \x01(\x05\x12\x0c\n\x04\x63urY\x18\x04 \x01(\x05\x12\x12\n\nwithBucket\x18\x05 \x01(\x08\x12\x12\n\nbucketCode\x18\x06 \x01(\t\x12\x0f\n\x07topFace\x18\x07 \x01(\x05\x12\n\n\x02ip\x18\x08 \x01(\t\x12\x0f\n\x07\x62uildNo\x18\t \x01(\t\x12S\n\x08typeEnum\x18\n \x01(\x0e\x32\x41.AgvRegisterRequestMessage.AgvRegisterRequest.AgvRegisterTypeEnum\x12L\n\x08\x64spState\x18\x0b \x01(\x0e\x32:.AgvRegisterRequestMessage.AgvRegisterRequest.AgvStateEnum\"X\n\x13\x41gvRegisterTypeEnum\x12\x14\n\x10REGISTER_NETWORK\x10\x00\x12\x13\n\x0fREGISTER_REBOOT\x10\x01\x12\x16\n\x12REGISTER_OPERATION\x10\x02\";\n\x0c\x41gvStateEnum\x12\x08\n\x04IDLE\x10\x00\x12\x08\n\x04\x42USY\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0c\n\x08\x43HARGING\x10\x03\x42\x46\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x17\x41gvRegisterRequestProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])



_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVREGISTERTYPEENUM = _descriptor.EnumDescriptor(
  name='AgvRegisterTypeEnum',
  full_name='AgvRegisterRequestMessage.AgvRegisterRequest.AgvRegisterTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGISTER_NETWORK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER_REBOOT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER_OPERATION', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=523,
  serialized_end=611,
)
_sym_db.RegisterEnumDescriptor(_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVREGISTERTYPEENUM)

_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVSTATEENUM = _descriptor.EnumDescriptor(
  name='AgvStateEnum',
  full_name='AgvRegisterRequestMessage.AgvRegisterRequest.AgvStateEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHARGING', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=613,
  serialized_end=672,
)
_sym_db.RegisterEnumDescriptor(_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVSTATEENUM)


_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST = _descriptor.Descriptor(
  name='AgvRegisterRequest',
  full_name='AgvRegisterRequestMessage.AgvRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agvCode', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.agvCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initPower', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.initPower', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curX', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.curX', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curY', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.curY', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withBucket', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.withBucket', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bucketCode', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.bucketCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topFace', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.topFace', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.ip', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buildNo', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.buildNo', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeEnum', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.typeEnum', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dspState', full_name='AgvRegisterRequestMessage.AgvRegisterRequest.dspState', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVREGISTERTYPEENUM,
    _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVSTATEENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=672,
)

_AGVREGISTERREQUESTMESSAGE = _descriptor.Descriptor(
  name='AgvRegisterRequestMessage',
  full_name='AgvRegisterRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='AgvRegisterRequestMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agvRegisterRequest', full_name='AgvRegisterRequestMessage.agvRegisterRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=672,
)

_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST.fields_by_name['typeEnum'].enum_type = _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVREGISTERTYPEENUM
_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST.fields_by_name['dspState'].enum_type = _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVSTATEENUM
_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST.containing_type = _AGVREGISTERREQUESTMESSAGE
_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVREGISTERTYPEENUM.containing_type = _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST
_AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST_AGVSTATEENUM.containing_type = _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST
_AGVREGISTERREQUESTMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_AGVREGISTERREQUESTMESSAGE.fields_by_name['agvRegisterRequest'].message_type = _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST
DESCRIPTOR.message_types_by_name['AgvRegisterRequestMessage'] = _AGVREGISTERREQUESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgvRegisterRequestMessage = _reflection.GeneratedProtocolMessageType('AgvRegisterRequestMessage', (_message.Message,), dict(

  AgvRegisterRequest = _reflection.GeneratedProtocolMessageType('AgvRegisterRequest', (_message.Message,), dict(
    DESCRIPTOR = _AGVREGISTERREQUESTMESSAGE_AGVREGISTERREQUEST,
    __module__ = 'AgvRegisterRequest_pb2'
    # @@protoc_insertion_point(class_scope:AgvRegisterRequestMessage.AgvRegisterRequest)
    ))
  ,
  DESCRIPTOR = _AGVREGISTERREQUESTMESSAGE,
  __module__ = 'AgvRegisterRequest_pb2'
  # @@protoc_insertion_point(class_scope:AgvRegisterRequestMessage)
  ))
_sym_db.RegisterMessage(AgvRegisterRequestMessage)
_sym_db.RegisterMessage(AgvRegisterRequestMessage.AgvRegisterRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
