# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgvRegisterResponseMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgvRegisterResponseMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\030AgvRegisterResponseProto'),
  serialized_pb=_b('\n AgvRegisterResponseMessage.proto\x1a\x11MessageBase.proto\"\xf3\x01\n\x1a\x41gvRegisterResponseMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12L\n\x13\x61gvRegisterResponse\x18\x02 \x01(\x0b\x32/.AgvRegisterResponseMessage.AgvRegisterResponse\x1a\x64\n\x13\x41gvRegisterResponse\x12\x0f\n\x07\x61gvCode\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0e\n\x06pixelX\x18\x05 \x01(\x01\x12\x0e\n\x06pixelY\x18\x06 \x01(\x01\x42G\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x18\x41gvRegisterResponseProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])




_AGVREGISTERRESPONSEMESSAGE_AGVREGISTERRESPONSE = _descriptor.Descriptor(
  name='AgvRegisterResponse',
  full_name='AgvRegisterResponseMessage.AgvRegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agvCode', full_name='AgvRegisterResponseMessage.AgvRegisterResponse.agvCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='AgvRegisterResponseMessage.AgvRegisterResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='AgvRegisterResponseMessage.AgvRegisterResponse.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixelX', full_name='AgvRegisterResponseMessage.AgvRegisterResponse.pixelX', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixelY', full_name='AgvRegisterResponseMessage.AgvRegisterResponse.pixelY', index=4,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=299,
)

_AGVREGISTERRESPONSEMESSAGE = _descriptor.Descriptor(
  name='AgvRegisterResponseMessage',
  full_name='AgvRegisterResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='AgvRegisterResponseMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agvRegisterResponse', full_name='AgvRegisterResponseMessage.agvRegisterResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGVREGISTERRESPONSEMESSAGE_AGVREGISTERRESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=299,
)

_AGVREGISTERRESPONSEMESSAGE_AGVREGISTERRESPONSE.containing_type = _AGVREGISTERRESPONSEMESSAGE
_AGVREGISTERRESPONSEMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_AGVREGISTERRESPONSEMESSAGE.fields_by_name['agvRegisterResponse'].message_type = _AGVREGISTERRESPONSEMESSAGE_AGVREGISTERRESPONSE
DESCRIPTOR.message_types_by_name['AgvRegisterResponseMessage'] = _AGVREGISTERRESPONSEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgvRegisterResponseMessage = _reflection.GeneratedProtocolMessageType('AgvRegisterResponseMessage', (_message.Message,), dict(

  AgvRegisterResponse = _reflection.GeneratedProtocolMessageType('AgvRegisterResponse', (_message.Message,), dict(
    DESCRIPTOR = _AGVREGISTERRESPONSEMESSAGE_AGVREGISTERRESPONSE,
    __module__ = 'AgvRegisterResponseMessage_pb2'
    # @@protoc_insertion_point(class_scope:AgvRegisterResponseMessage.AgvRegisterResponse)
    ))
  ,
  DESCRIPTOR = _AGVREGISTERRESPONSEMESSAGE,
  __module__ = 'AgvRegisterResponseMessage_pb2'
  # @@protoc_insertion_point(class_scope:AgvRegisterResponseMessage)
  ))
_sym_db.RegisterMessage(AgvRegisterResponseMessage)
_sym_db.RegisterMessage(AgvRegisterResponseMessage.AgvRegisterResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
