# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgvUnRegisterRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgvUnRegisterRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\031AgvUnRegisterRequestProto'),
  serialized_pb=_b('\n\x1a\x41gvUnRegisterRequest.proto\x1a\x11MessageBase.proto\"\x81\x03\n\x1b\x41gvUnRegisterRequestMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12O\n\x14\x61gvUnRegisterRequest\x18\x02 \x01(\x0b\x32\x31.AgvUnRegisterRequestMessage.AgvUnRegisterRequest\x1a\xed\x01\n\x14\x41gvUnRegisterRequest\x12\x0f\n\x07\x61gvCode\x18\x01 \x01(\t\x12\x63\n\x12unRegisterTypeEnum\x18\x02 \x01(\x0e\x32G.AgvUnRegisterRequestMessage.AgvUnRegisterRequest.AgvUnRegisterTypeEnum\x12\x0f\n\x07message\x18\x03 \x01(\t\"N\n\x15\x41gvUnRegisterTypeEnum\x12\x19\n\x15UNREGISTER_BASIC_TYPE\x10\x00\x12\x1a\n\x16UNREGISTER_ONLINE_TYPE\x10\x01\x42H\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x19\x41gvUnRegisterRequestProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])



_AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST_AGVUNREGISTERTYPEENUM = _descriptor.EnumDescriptor(
  name='AgvUnRegisterTypeEnum',
  full_name='AgvUnRegisterRequestMessage.AgvUnRegisterRequest.AgvUnRegisterTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNREGISTER_BASIC_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNREGISTER_ONLINE_TYPE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=435,
)
_sym_db.RegisterEnumDescriptor(_AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST_AGVUNREGISTERTYPEENUM)


_AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST = _descriptor.Descriptor(
  name='AgvUnRegisterRequest',
  full_name='AgvUnRegisterRequestMessage.AgvUnRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agvCode', full_name='AgvUnRegisterRequestMessage.AgvUnRegisterRequest.agvCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unRegisterTypeEnum', full_name='AgvUnRegisterRequestMessage.AgvUnRegisterRequest.unRegisterTypeEnum', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='AgvUnRegisterRequestMessage.AgvUnRegisterRequest.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST_AGVUNREGISTERTYPEENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=435,
)

_AGVUNREGISTERREQUESTMESSAGE = _descriptor.Descriptor(
  name='AgvUnRegisterRequestMessage',
  full_name='AgvUnRegisterRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='AgvUnRegisterRequestMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agvUnRegisterRequest', full_name='AgvUnRegisterRequestMessage.agvUnRegisterRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=435,
)

_AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST.fields_by_name['unRegisterTypeEnum'].enum_type = _AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST_AGVUNREGISTERTYPEENUM
_AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST.containing_type = _AGVUNREGISTERREQUESTMESSAGE
_AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST_AGVUNREGISTERTYPEENUM.containing_type = _AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST
_AGVUNREGISTERREQUESTMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_AGVUNREGISTERREQUESTMESSAGE.fields_by_name['agvUnRegisterRequest'].message_type = _AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST
DESCRIPTOR.message_types_by_name['AgvUnRegisterRequestMessage'] = _AGVUNREGISTERREQUESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgvUnRegisterRequestMessage = _reflection.GeneratedProtocolMessageType('AgvUnRegisterRequestMessage', (_message.Message,), dict(

  AgvUnRegisterRequest = _reflection.GeneratedProtocolMessageType('AgvUnRegisterRequest', (_message.Message,), dict(
    DESCRIPTOR = _AGVUNREGISTERREQUESTMESSAGE_AGVUNREGISTERREQUEST,
    __module__ = 'AgvUnRegisterRequest_pb2'
    # @@protoc_insertion_point(class_scope:AgvUnRegisterRequestMessage.AgvUnRegisterRequest)
    ))
  ,
  DESCRIPTOR = _AGVUNREGISTERREQUESTMESSAGE,
  __module__ = 'AgvUnRegisterRequest_pb2'
  # @@protoc_insertion_point(class_scope:AgvUnRegisterRequestMessage)
  ))
_sym_db.RegisterMessage(AgvUnRegisterRequestMessage)
_sym_db.RegisterMessage(AgvUnRegisterRequestMessage.AgvUnRegisterRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
