# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageBase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageBase.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\020MessageBaseProto'),
  serialized_pb=_b('\n\x11MessageBase.proto\"\xf7\x03\n\x0bMessageBase\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\x0fmessageTypeEnum\x18\x02 \x01(\x0e\x32\x1c.MessageBase.MessageTypeEnum\x12#\n\x07mapping\x18\x03 \x01(\x0b\x32\x12.MessageBase.Model\x12\x19\n\x11respTimeoutMillis\x18\x04 \x01(\x03\x12\x17\n\x0f\x63ollaborationId\x18\x05 \x01(\t\x12\x10\n\x08\x65rrorMsg\x18\x06 \x01(\t\x12\x12\n\nnetStartTm\x18\x07 \x01(\x03\x12\x10\n\x08netEndTm\x18\x08 \x01(\x03\x1a\xcf\x01\n\x05Model\x12\x0c\n\x04path\x18\x01 \x01(\t\x12-\n\x08modeEnum\x18\x02 \x01(\x0e\x32\x1b.MessageBase.Model.ModeEnum\x12-\n\x08typeEnum\x18\x03 \x01(\x0e\x32\x1b.MessageBase.Model.TypeEnum\"\x1f\n\x08ModeEnum\x12\x08\n\x04SYNC\x10\x00\x12\t\n\x05\x41SYNC\x10\x01\"9\n\x08TypeEnum\x12\x0b\n\x07REQUEST\x10\x00\x12\n\n\x06REPORT\x10\x01\x12\x08\n\x04PUSH\x10\x02\x12\n\n\x06NOTIFY\x10\x03\"B\n\x0fMessageTypeEnum\x12\x08\n\x04INIT\x10\x00\x12\x0e\n\nHEART_BEAT\x10\x01\x12\x08\n\x04\x44\x41TA\x10\x02\x12\x0b\n\x07\x44\x45STROY\x10\x03\x42?\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x10MessageBaseProtob\x06proto3')
)



_MESSAGEBASE_MODEL_MODEENUM = _descriptor.EnumDescriptor(
  name='ModeEnum',
  full_name='MessageBase.Model.ModeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYNC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASYNC', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=367,
  serialized_end=398,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEBASE_MODEL_MODEENUM)

_MESSAGEBASE_MODEL_TYPEENUM = _descriptor.EnumDescriptor(
  name='TypeEnum',
  full_name='MessageBase.Model.TypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUSH', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=400,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEBASE_MODEL_TYPEENUM)

_MESSAGEBASE_MESSAGETYPEENUM = _descriptor.EnumDescriptor(
  name='MessageTypeEnum',
  full_name='MessageBase.MessageTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_BEAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DESTROY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=459,
  serialized_end=525,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEBASE_MESSAGETYPEENUM)


_MESSAGEBASE_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='MessageBase.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='MessageBase.Model.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modeEnum', full_name='MessageBase.Model.modeEnum', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeEnum', full_name='MessageBase.Model.typeEnum', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGEBASE_MODEL_MODEENUM,
    _MESSAGEBASE_MODEL_TYPEENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=457,
)

_MESSAGEBASE = _descriptor.Descriptor(
  name='MessageBase',
  full_name='MessageBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MessageBase.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageTypeEnum', full_name='MessageBase.messageTypeEnum', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapping', full_name='MessageBase.mapping', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='respTimeoutMillis', full_name='MessageBase.respTimeoutMillis', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collaborationId', full_name='MessageBase.collaborationId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorMsg', full_name='MessageBase.errorMsg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='netStartTm', full_name='MessageBase.netStartTm', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='netEndTm', full_name='MessageBase.netEndTm', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGEBASE_MODEL, ],
  enum_types=[
    _MESSAGEBASE_MESSAGETYPEENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=525,
)

_MESSAGEBASE_MODEL.fields_by_name['modeEnum'].enum_type = _MESSAGEBASE_MODEL_MODEENUM
_MESSAGEBASE_MODEL.fields_by_name['typeEnum'].enum_type = _MESSAGEBASE_MODEL_TYPEENUM
_MESSAGEBASE_MODEL.containing_type = _MESSAGEBASE
_MESSAGEBASE_MODEL_MODEENUM.containing_type = _MESSAGEBASE_MODEL
_MESSAGEBASE_MODEL_TYPEENUM.containing_type = _MESSAGEBASE_MODEL
_MESSAGEBASE.fields_by_name['messageTypeEnum'].enum_type = _MESSAGEBASE_MESSAGETYPEENUM
_MESSAGEBASE.fields_by_name['mapping'].message_type = _MESSAGEBASE_MODEL
_MESSAGEBASE_MESSAGETYPEENUM.containing_type = _MESSAGEBASE
DESCRIPTOR.message_types_by_name['MessageBase'] = _MESSAGEBASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageBase = _reflection.GeneratedProtocolMessageType('MessageBase', (_message.Message,), dict(

  Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGEBASE_MODEL,
    __module__ = 'MessageBase_pb2'
    # @@protoc_insertion_point(class_scope:MessageBase.Model)
    ))
  ,
  DESCRIPTOR = _MESSAGEBASE,
  __module__ = 'MessageBase_pb2'
  # @@protoc_insertion_point(class_scope:MessageBase)
  ))
_sym_db.RegisterMessage(MessageBase)
_sym_db.RegisterMessage(MessageBase.Model)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
