# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionDestroyInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SessionDestroyInfo.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\027SessionDestroyInfoProto'),
  serialized_pb=_b('\n\x18SessionDestroyInfo.proto\x1a\x11MessageBase.proto\"\xf9\x01\n\x19SessionDestroyInfoMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12I\n\x12sessionDestroyInfo\x18\x02 \x01(\x0b\x32-.SessionDestroyInfoMessage.SessionDestroyInfo\x1an\n\x12SessionDestroyInfo\x12\x13\n\x0bsessionName\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x10\n\x08\x63onnName\x18\x03 \x01(\t\x12\x0e\n\x06\x63onnId\x18\x04 \x01(\t\x12\x0e\n\x06userId\x18\x05 \x01(\tBF\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x17SessionDestroyInfoProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])




_SESSIONDESTROYINFOMESSAGE_SESSIONDESTROYINFO = _descriptor.Descriptor(
  name='SessionDestroyInfo',
  full_name='SessionDestroyInfoMessage.SessionDestroyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionName', full_name='SessionDestroyInfoMessage.SessionDestroyInfo.sessionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='SessionDestroyInfoMessage.SessionDestroyInfo.sessionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connName', full_name='SessionDestroyInfoMessage.SessionDestroyInfo.connName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connId', full_name='SessionDestroyInfoMessage.SessionDestroyInfo.connId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='SessionDestroyInfoMessage.SessionDestroyInfo.userId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=297,
)

_SESSIONDESTROYINFOMESSAGE = _descriptor.Descriptor(
  name='SessionDestroyInfoMessage',
  full_name='SessionDestroyInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='SessionDestroyInfoMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionDestroyInfo', full_name='SessionDestroyInfoMessage.sessionDestroyInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SESSIONDESTROYINFOMESSAGE_SESSIONDESTROYINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=297,
)

_SESSIONDESTROYINFOMESSAGE_SESSIONDESTROYINFO.containing_type = _SESSIONDESTROYINFOMESSAGE
_SESSIONDESTROYINFOMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_SESSIONDESTROYINFOMESSAGE.fields_by_name['sessionDestroyInfo'].message_type = _SESSIONDESTROYINFOMESSAGE_SESSIONDESTROYINFO
DESCRIPTOR.message_types_by_name['SessionDestroyInfoMessage'] = _SESSIONDESTROYINFOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionDestroyInfoMessage = _reflection.GeneratedProtocolMessageType('SessionDestroyInfoMessage', (_message.Message,), dict(

  SessionDestroyInfo = _reflection.GeneratedProtocolMessageType('SessionDestroyInfo', (_message.Message,), dict(
    DESCRIPTOR = _SESSIONDESTROYINFOMESSAGE_SESSIONDESTROYINFO,
    __module__ = 'SessionDestroyInfo_pb2'
    # @@protoc_insertion_point(class_scope:SessionDestroyInfoMessage.SessionDestroyInfo)
    ))
  ,
  DESCRIPTOR = _SESSIONDESTROYINFOMESSAGE,
  __module__ = 'SessionDestroyInfo_pb2'
  # @@protoc_insertion_point(class_scope:SessionDestroyInfoMessage)
  ))
_sym_db.RegisterMessage(SessionDestroyInfoMessage)
_sym_db.RegisterMessage(SessionDestroyInfoMessage.SessionDestroyInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
