# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionRegisterInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageBase_pb2 as MessageBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SessionRegisterInfo.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\030SessionRegisterInfoProto'),
  serialized_pb=_b('\n\x19SessionRegisterInfo.proto\x1a\x11MessageBase.proto\"\xc0\x04\n\x1aSessionRegisterInfoMessage\x12!\n\x0bmessageBase\x18\x01 \x01(\x0b\x32\x0c.MessageBase\x12L\n\x13sessionRegisterInfo\x18\x02 \x01(\x0b\x32/.SessionRegisterInfoMessage.SessionRegisterInfo\x1a\xb0\x03\n\x13SessionRegisterInfo\x12\x13\n\x0bsessionName\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x13\n\x0bsessionSize\x18\x03 \x01(\x05\x12\x64\n\x15heartbeatStrategyEnum\x18\x04 \x01(\x0e\x32\x45.SessionRegisterInfoMessage.SessionRegisterInfo.HeartbeatStrategyEnum\x12\x13\n\x0b\x61llIdleTime\x18\x05 \x01(\x03\x12\x14\n\x0cidleTimeUnit\x18\x06 \x01(\t\x12\x0f\n\x07timeout\x18\x07 \x01(\x03\x12\x10\n\x08\x63onnName\x18\x08 \x01(\t\x12\x0e\n\x06\x63onnId\x18\t \x01(\t\x12\x17\n\x0fisHeartbeatConn\x18\n \x01(\x08\x12\x13\n\x0bpathMatcher\x18\x0b \x01(\t\x12\x13\n\x0b\x64\x65\x66\x61ultConn\x18\x0c \x01(\x08\x12\x0e\n\x06userId\x18\r \x01(\t\"E\n\x15HeartbeatStrategyEnum\x12\x15\n\x11\x43LIENT_INITIATIVE\x10\x00\x12\x15\n\x11SERVER_INITIATIVE\x10\x01\x42G\n+com.cainiao.swarm.urcs.msg.bus.client.protoB\x18SessionRegisterInfoProtob\x06proto3')
  ,
  dependencies=[MessageBase__pb2.DESCRIPTOR,])



_SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO_HEARTBEATSTRATEGYENUM = _descriptor.EnumDescriptor(
  name='HeartbeatStrategyEnum',
  full_name='SessionRegisterInfoMessage.SessionRegisterInfo.HeartbeatStrategyEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIENT_INITIATIVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_INITIATIVE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=556,
  serialized_end=625,
)
_sym_db.RegisterEnumDescriptor(_SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO_HEARTBEATSTRATEGYENUM)


_SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO = _descriptor.Descriptor(
  name='SessionRegisterInfo',
  full_name='SessionRegisterInfoMessage.SessionRegisterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionName', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.sessionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.sessionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionSize', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.sessionSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeatStrategyEnum', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.heartbeatStrategyEnum', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allIdleTime', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.allIdleTime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idleTimeUnit', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.idleTimeUnit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.timeout', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connName', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.connName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connId', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.connId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isHeartbeatConn', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.isHeartbeatConn', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pathMatcher', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.pathMatcher', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='defaultConn', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.defaultConn', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='SessionRegisterInfoMessage.SessionRegisterInfo.userId', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO_HEARTBEATSTRATEGYENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=625,
)

_SESSIONREGISTERINFOMESSAGE = _descriptor.Descriptor(
  name='SessionRegisterInfoMessage',
  full_name='SessionRegisterInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageBase', full_name='SessionRegisterInfoMessage.messageBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionRegisterInfo', full_name='SessionRegisterInfoMessage.sessionRegisterInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=625,
)

_SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO.fields_by_name['heartbeatStrategyEnum'].enum_type = _SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO_HEARTBEATSTRATEGYENUM
_SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO.containing_type = _SESSIONREGISTERINFOMESSAGE
_SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO_HEARTBEATSTRATEGYENUM.containing_type = _SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO
_SESSIONREGISTERINFOMESSAGE.fields_by_name['messageBase'].message_type = MessageBase__pb2._MESSAGEBASE
_SESSIONREGISTERINFOMESSAGE.fields_by_name['sessionRegisterInfo'].message_type = _SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO
DESCRIPTOR.message_types_by_name['SessionRegisterInfoMessage'] = _SESSIONREGISTERINFOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionRegisterInfoMessage = _reflection.GeneratedProtocolMessageType('SessionRegisterInfoMessage', (_message.Message,), dict(

  SessionRegisterInfo = _reflection.GeneratedProtocolMessageType('SessionRegisterInfo', (_message.Message,), dict(
    DESCRIPTOR = _SESSIONREGISTERINFOMESSAGE_SESSIONREGISTERINFO,
    __module__ = 'SessionRegisterInfo_pb2'
    # @@protoc_insertion_point(class_scope:SessionRegisterInfoMessage.SessionRegisterInfo)
    ))
  ,
  DESCRIPTOR = _SESSIONREGISTERINFOMESSAGE,
  __module__ = 'SessionRegisterInfo_pb2'
  # @@protoc_insertion_point(class_scope:SessionRegisterInfoMessage)
  ))
_sym_db.RegisterMessage(SessionRegisterInfoMessage)
_sym_db.RegisterMessage(SessionRegisterInfoMessage.SessionRegisterInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
